# Generated by Django 5.2.7 on 2025-12-25 10:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='pyment_status',
            new_name='status',
        ),
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
